services:
  - type: web
    name: compintel-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
